# build node-gyp modules in different stage
FROM node:10-alpine as build-stage

RUN apk add --no-cache git gcc g++ python make musl-dev

COPY package.json yarn.lock ./
COPY frontend/ ./frontend/

RUN yarn install

# production stage
FROM node:10-alpine

COPY --from=build-stage node_modules ./frontend/node_modules

COPY frontend/ ./frontend/
COPY backend/models/relationId.json ./backend/models/relationId.json

WORKDIR frontend

CMD ["yarn", "serve"]
