# build node-gyp modules in different stage
FROM node:10-alpine as build-stage

COPY package.json yarn.lock ./
COPY frontend/ ./frontend/

RUN yarn install

# production stage
FROM node:10-alpine

COPY --from=build-stage node_modules ./frontend/node_modules

COPY frontend/ ./frontend/

WORKDIR frontend

CMD ["yarn", "serve"]
