# build node-gyp modules in different stage
FROM node:10-alpine as build-stage

COPY package.json yarn.lock ./
COPY frontend/ ./frontend/
COPY backend/models/relationId.json ./backend/models/relationId.json

RUN yarn install --prod

RUN cd frontend && yarn build

# production stage
FROM node:10-alpine

RUN yarn global add http-server spa-http-server

COPY --from=build-stage /frontend/dist /

CMD ["http-server", "--push-state", "-c-0", "-p 8080"]
